### ISSUE TITLE
Provide a form to easily enter details reported at the regular meeting   

### ISSUE THREAD

**Issue by anthonyhowlett** [ObsidianRock/remap#4]
Following on from the "Date Reported" issue.  Its likely that a number of comments will be entered at one time and it would be mighty handy to have a a input form with many rows with the following column headings.
Date Noted      Project Number       Comment        Project status

 For example I'd enter the date of the meeting in the Date Noted column, select the project number from drop down list of all open/awaiting volunteers projects, then type in under comments all the stuff reported at the meeting for each project and finally select a status from a dropdown list (from a table of possible project statuses eg finished, closed, on hold, awaiting volunteer, ongoing).

**Comment by ObsidianRock** [comment]
Will this be a different page, for example a page just for meetings? just like we have a page for single projects.

**Comment by anthonyhowlett** [comment]
Hi Mustafa 

 

Yes I see it as a form with the meeting date at the top – so input once  - and then rows of project number – meeting comments. Which results in the db being updated for each project number with the meeting date (ie date noted field) the comments. We could then produce a pdf list for each meeting which could be email ahead of the meeting. The list would be Project Heading detail (Number, Title, Date Initially Contacted) followed by previous comments(latest comments first). The list should be sorted project number within Volunteer Name.     

 

Best Regards

 

Tony

01883 622262

07956 316253
