### ISSUE TITLE
Creation and Modification Timestamp on every record in each table 

### ISSUE THREAD

**Issue by anthonyhowlett** [ObsidianRock/remap#6]
As a standard please automatically record a date/time stamp on every record showing when it was created and also when it was last modified

**Comment by ObsidianRock** [comment]
Which records or pages are you refering to? I assume it is for the printed PDF

**Comment by anthonyhowlett** [comment]
Mustafa 

 

Hi I think we put a time stamp on every database record whenb its created but we don’t have a timestamp the last time it was changed. That would be useful as would the name of the person who was logged in when the database record was created and when it was last changed.

 

Best Regards

 

Tony

01883 622262

07956 316253
